/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.daos;


import com.guoguo.domain.jooq.tables.TPermission;
import com.guoguo.domain.jooq.tables.pojos.TPermissionObj;
import com.guoguo.domain.jooq.tables.records.TPermissionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TPermissionDao extends DAOImpl<TPermissionRecord, TPermissionObj, Integer> {

    /**
     * Create a new TPermissionDao without any configuration
     */
    public TPermissionDao() {
        super(TPermission.T_PERMISSION, TPermissionObj.class);
    }

    /**
     * Create a new TPermissionDao with an attached configuration
     */
    @Autowired
    public TPermissionDao(Configuration configuration) {
        super(TPermission.T_PERMISSION, TPermissionObj.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(TPermissionObj object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<TPermissionObj> fetchById(Integer... values) {
        return fetch(TPermission.T_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public TPermissionObj fetchOneById(Integer value) {
        return fetchOne(TPermission.T_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<TPermissionObj> fetchByName(String... values) {
        return fetch(TPermission.T_PERMISSION.NAME, values);
    }

    /**
     * Fetch records that have <code>resource_type IN (values)</code>
     */
    public List<TPermissionObj> fetchByResourceType(String... values) {
        return fetch(TPermission.T_PERMISSION.RESOURCE_TYPE, values);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<TPermissionObj> fetchByPermission(String... values) {
        return fetch(TPermission.T_PERMISSION.PERMISSION, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<TPermissionObj> fetchByUrl(String... values) {
        return fetch(TPermission.T_PERMISSION.URL, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<TPermissionObj> fetchByParentId(Integer... values) {
        return fetch(TPermission.T_PERMISSION.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<TPermissionObj> fetchBySort(Byte... values) {
        return fetch(TPermission.T_PERMISSION.SORT, values);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<TPermissionObj> fetchByIcon(String... values) {
        return fetch(TPermission.T_PERMISSION.ICON, values);
    }

    /**
     * Fetch records that have <code>insert_time IN (values)</code>
     */
    public List<TPermissionObj> fetchByInsertTime(Timestamp... values) {
        return fetch(TPermission.T_PERMISSION.INSERT_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<TPermissionObj> fetchByUpdateTime(Timestamp... values) {
        return fetch(TPermission.T_PERMISSION.UPDATE_TIME, values);
    }
}
