server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guoguo?characterEncoding=utf8&useSSL=false
    username: root
    password: liudaroot
  jooq:
    sql-dialect: mysql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
  path: C:/logs/guomu.log
  file:
    max-size: 10MB










