/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq;


import com.guoguo.domain.jooq.tables.TPermission;
import com.guoguo.domain.jooq.tables.TRole;
import com.guoguo.domain.jooq.tables.TRolePermission;
import com.guoguo.domain.jooq.tables.TUser;
import com.guoguo.domain.jooq.tables.TUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guoguo extends SchemaImpl {

    private static final long serialVersionUID = -1577505813;

    /**
     * The reference instance of <code>guoguo</code>
     */
    public static final Guoguo GUOGUO = new Guoguo();

    /**
     * 权限表
     */
    public final TPermission T_PERMISSION = com.guoguo.domain.jooq.tables.TPermission.T_PERMISSION;

    /**
     * 角色表
     */
    public final TRole T_ROLE = com.guoguo.domain.jooq.tables.TRole.T_ROLE;

    /**
     * 角色权限表
     */
    public final TRolePermission T_ROLE_PERMISSION = com.guoguo.domain.jooq.tables.TRolePermission.T_ROLE_PERMISSION;

    /**
     * 用户表
     */
    public final TUser T_USER = com.guoguo.domain.jooq.tables.TUser.T_USER;

    /**
     * 用户角色表
     */
    public final TUserRole T_USER_ROLE = com.guoguo.domain.jooq.tables.TUserRole.T_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Guoguo() {
        super("guoguo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TPermission.T_PERMISSION,
            TRole.T_ROLE,
            TRolePermission.T_ROLE_PERMISSION,
            TUser.T_USER,
            TUserRole.T_USER_ROLE);
    }
}
