/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq;


import com.guoguo.domain.jooq.tables.TUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guoguo extends SchemaImpl {

    private static final long serialVersionUID = -1899859441;

    /**
     * The reference instance of <code>guoguo</code>
     */
    public static final Guoguo GUOGUO = new Guoguo();

    /**
     * 用户表
     */
    public final TUser T_USER = com.guoguo.domain.jooq.tables.TUser.T_USER;

    /**
     * No further instances allowed
     */
    private Guoguo() {
        super("guoguo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
