/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq;


import com.guoguo.domain.jooq.tables.TUser;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>guoguo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_USER_PHONE = Indexes0.T_USER_PHONE;
    public static final Index T_USER_PRIMARY = Indexes0.T_USER_PRIMARY;
    public static final Index T_USER_USERNAME = Indexes0.T_USER_USERNAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_USER_PHONE = Internal.createIndex("phone", TUser.T_USER, new OrderField[] { TUser.T_USER.PHONE }, true);
        public static Index T_USER_PRIMARY = Internal.createIndex("PRIMARY", TUser.T_USER, new OrderField[] { TUser.T_USER.ID }, true);
        public static Index T_USER_USERNAME = Internal.createIndex("username", TUser.T_USER, new OrderField[] { TUser.T_USER.USERNAME }, true);
    }
}
