/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq;


import com.guoguo.domain.jooq.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in guoguo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户表
     */
    public static final TUser T_USER = com.guoguo.domain.jooq.tables.TUser.T_USER;
}
