/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq;


import com.guoguo.domain.jooq.tables.TPermission;
import com.guoguo.domain.jooq.tables.TRole;
import com.guoguo.domain.jooq.tables.TRolePermission;
import com.guoguo.domain.jooq.tables.TUser;
import com.guoguo.domain.jooq.tables.TUserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in guoguo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 权限表
     */
    public static final TPermission T_PERMISSION = com.guoguo.domain.jooq.tables.TPermission.T_PERMISSION;

    /**
     * 角色表
     */
    public static final TRole T_ROLE = com.guoguo.domain.jooq.tables.TRole.T_ROLE;

    /**
     * 角色权限表
     */
    public static final TRolePermission T_ROLE_PERMISSION = com.guoguo.domain.jooq.tables.TRolePermission.T_ROLE_PERMISSION;

    /**
     * 用户表
     */
    public static final TUser T_USER = com.guoguo.domain.jooq.tables.TUser.T_USER;

    /**
     * 用户角色表
     */
    public static final TUserRole T_USER_ROLE = com.guoguo.domain.jooq.tables.TUserRole.T_USER_ROLE;
}
