/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.records;


import com.guoguo.domain.jooq.tables.TPermission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPermissionRecord extends UpdatableRecordImpl<TPermissionRecord> implements Record10<Integer, String, String, String, String, Integer, Byte, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 838693400;

    /**
     * Setter for <code>guoguo.t_permission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>guoguo.t_permission.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>guoguo.t_permission.resource_type</code>. 权限分类（0 菜单；1 功能）
     */
    public void setResourceType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.resource_type</code>. 权限分类（0 菜单；1 功能）
     */
    public String getResourceType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>guoguo.t_permission.permission</code>. 操作权限
     */
    public void setPermission(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.permission</code>. 操作权限
     */
    public String getPermission() {
        return (String) get(3);
    }

    /**
     * Setter for <code>guoguo.t_permission.url</code>. 资源路径
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.url</code>. 资源路径
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>guoguo.t_permission.parent_id</code>. 父id
     */
    public void setParentId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.parent_id</code>. 父id
     */
    public Integer getParentId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>guoguo.t_permission.sort</code>. 排序
     */
    public void setSort(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.sort</code>. 排序
     */
    public Byte getSort() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>guoguo.t_permission.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(7);
    }

    /**
     * Setter for <code>guoguo.t_permission.insert_time</code>. 添加时间
     */
    public void setInsertTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.insert_time</code>. 添加时间
     */
    public Timestamp getInsertTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>guoguo.t_permission.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>guoguo.t_permission.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Integer, Byte, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Integer, Byte, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPermission.T_PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPermission.T_PERMISSION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPermission.T_PERMISSION.RESOURCE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPermission.T_PERMISSION.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TPermission.T_PERMISSION.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TPermission.T_PERMISSION.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TPermission.T_PERMISSION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TPermission.T_PERMISSION.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TPermission.T_PERMISSION.INSERT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TPermission.T_PERMISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getResourceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getInsertTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getResourceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getInsertTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value3(String value) {
        setResourceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value4(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value6(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value7(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value8(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value9(Timestamp value) {
        setInsertTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value10(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Byte value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPermissionRecord
     */
    public TPermissionRecord() {
        super(TPermission.T_PERMISSION);
    }

    /**
     * Create a detached, initialised TPermissionRecord
     */
    public TPermissionRecord(Integer id, String name, String resourceType, String permission, String url, Integer parentId, Byte sort, String icon, Timestamp insertTime, Timestamp updateTime) {
        super(TPermission.T_PERMISSION);

        set(0, id);
        set(1, name);
        set(2, resourceType);
        set(3, permission);
        set(4, url);
        set(5, parentId);
        set(6, sort);
        set(7, icon);
        set(8, insertTime);
        set(9, updateTime);
    }
}
