/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.records;


import com.guoguo.domain.jooq.tables.TUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> {

    private static final long serialVersionUID = 717713811;

    /**
     * Setter for <code>guoguo.t_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>guoguo.t_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>guoguo.t_user.username</code>. 登陆名
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>guoguo.t_user.username</code>. 登陆名
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>guoguo.t_user.password</code>. 登陆密码，加密存储
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>guoguo.t_user.password</code>. 登陆密码，加密存储
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>guoguo.t_user.real_name</code>. 真实姓名
     */
    public void setRealName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>guoguo.t_user.real_name</code>. 真实姓名
     */
    public String getRealName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>guoguo.t_user.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>guoguo.t_user.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>guoguo.t_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>guoguo.t_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>guoguo.t_user.qq_num</code>. qq号
     */
    public void setQqNum(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>guoguo.t_user.qq_num</code>. qq号
     */
    public String getQqNum() {
        return (String) get(6);
    }

    /**
     * Setter for <code>guoguo.t_user.wechat_num</code>. 微信号
     */
    public void setWechatNum(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>guoguo.t_user.wechat_num</code>. 微信号
     */
    public String getWechatNum() {
        return (String) get(7);
    }

    /**
     * Setter for <code>guoguo.t_user.score</code>. 用户积分
     */
    public void setScore(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>guoguo.t_user.score</code>. 用户积分
     */
    public Integer getScore() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>guoguo.t_user.career_type</code>. 职业类型
     */
    public void setCareerType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>guoguo.t_user.career_type</code>. 职业类型
     */
    public String getCareerType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>guoguo.t_user.work_time</code>. 工作年限
     */
    public void setWorkTime(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>guoguo.t_user.work_time</code>. 工作年限
     */
    public Integer getWorkTime() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>guoguo.t_user.specialty</code>. 擅长
     */
    public void setSpecialty(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>guoguo.t_user.specialty</code>. 擅长
     */
    public String getSpecialty() {
        return (String) get(11);
    }

    /**
     * Setter for <code>guoguo.t_user.intro</code>. 简介
     */
    public void setIntro(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>guoguo.t_user.intro</code>. 简介
     */
    public String getIntro() {
        return (String) get(12);
    }

    /**
     * Setter for <code>guoguo.t_user.user_url</code>. 个人网址
     */
    public void setUserUrl(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>guoguo.t_user.user_url</code>. 个人网址
     */
    public String getUserUrl() {
        return (String) get(13);
    }

    /**
     * Setter for <code>guoguo.t_user.icon</code>. 头像
     */
    public void setIcon(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>guoguo.t_user.icon</code>. 头像
     */
    public String getIcon() {
        return (String) get(14);
    }

    /**
     * Setter for <code>guoguo.t_user.sex</code>. 性别：1-男，2-女，3-保密
     */
    public void setSex(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>guoguo.t_user.sex</code>. 性别：1-男，2-女，3-保密
     */
    public String getSex() {
        return (String) get(15);
    }

    /**
     * Setter for <code>guoguo.t_user.address</code>. 地址
     */
    public void setAddress(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>guoguo.t_user.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(16);
    }

    /**
     * Setter for <code>guoguo.t_user.status</code>. 用户帐号状态：1-正常，2-锁定,3-删除
     */
    public void setStatus(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>guoguo.t_user.status</code>. 用户帐号状态：1-正常，2-锁定,3-删除
     */
    public Integer getStatus() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>guoguo.t_user.mcode</code>. 短信验证码
     */
    public void setMcode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>guoguo.t_user.mcode</code>. 短信验证码
     */
    public String getMcode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>guoguo.t_user.send_time</code>. 短信发送时间
     */
    public void setSendTime(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>guoguo.t_user.send_time</code>. 短信发送时间
     */
    public Timestamp getSendTime() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>guoguo.t_user.create_time</code>. 创建时间
     */
    public void setCreateTime(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>guoguo.t_user.create_time</code>. 创建时间
     */
    public String getCreateTime() {
        return (String) get(20);
    }

    /**
     * Setter for <code>guoguo.t_user.create_user</code>. 创建人
     */
    public void setCreateUser(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>guoguo.t_user.create_user</code>. 创建人
     */
    public String getCreateUser() {
        return (String) get(21);
    }

    /**
     * Setter for <code>guoguo.t_user.update_time</code>. 更新时间
     */
    public void setUpdateTime(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>guoguo.t_user.update_time</code>. 更新时间
     */
    public String getUpdateTime() {
        return (String) get(22);
    }

    /**
     * Setter for <code>guoguo.t_user.update_user</code>. 更新人
     */
    public void setUpdateUser(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>guoguo.t_user.update_user</code>. 更新人
     */
    public String getUpdateUser() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(Integer id, String username, String password, String realName, String phone, String email, String qqNum, String wechatNum, Integer score, String careerType, Integer workTime, String specialty, String intro, String userUrl, String icon, String sex, String address, Integer status, String mcode, Timestamp sendTime, String createTime, String createUser, String updateTime, String updateUser) {
        super(TUser.T_USER);

        set(0, id);
        set(1, username);
        set(2, password);
        set(3, realName);
        set(4, phone);
        set(5, email);
        set(6, qqNum);
        set(7, wechatNum);
        set(8, score);
        set(9, careerType);
        set(10, workTime);
        set(11, specialty);
        set(12, intro);
        set(13, userUrl);
        set(14, icon);
        set(15, sex);
        set(16, address);
        set(17, status);
        set(18, mcode);
        set(19, sendTime);
        set(20, createTime);
        set(21, createUser);
        set(22, updateTime);
        set(23, updateUser);
    }
}
