/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPermissionObj implements Serializable {

    private static final long serialVersionUID = 1162042861;

    private Integer   id;
    private String    name;
    private String    resourceType;
    private String    permission;
    private String    url;
    private Integer   parentId;
    private Byte      sort;
    private String    icon;
    private Timestamp insertTime;
    private Timestamp updateTime;

    public TPermissionObj() {}

    public TPermissionObj(TPermissionObj value) {
        this.id = value.id;
        this.name = value.name;
        this.resourceType = value.resourceType;
        this.permission = value.permission;
        this.url = value.url;
        this.parentId = value.parentId;
        this.sort = value.sort;
        this.icon = value.icon;
        this.insertTime = value.insertTime;
        this.updateTime = value.updateTime;
    }

    public TPermissionObj(
        Integer   id,
        String    name,
        String    resourceType,
        String    permission,
        String    url,
        Integer   parentId,
        Byte      sort,
        String    icon,
        Timestamp insertTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.name = name;
        this.resourceType = resourceType;
        this.permission = permission;
        this.url = url;
        this.parentId = parentId;
        this.sort = sort;
        this.icon = icon;
        this.insertTime = insertTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResourceType() {
        return this.resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Byte getSort() {
        return this.sort;
    }

    public void setSort(Byte sort) {
        this.sort = sort;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Timestamp getInsertTime() {
        return this.insertTime;
    }

    public void setInsertTime(Timestamp insertTime) {
        this.insertTime = insertTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TPermissionObj other = (TPermissionObj) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (resourceType == null) {
            if (other.resourceType != null)
                return false;
        }
        else if (!resourceType.equals(other.resourceType))
            return false;
        if (permission == null) {
            if (other.permission != null)
                return false;
        }
        else if (!permission.equals(other.permission))
            return false;
        if (url == null) {
            if (other.url != null)
                return false;
        }
        else if (!url.equals(other.url))
            return false;
        if (parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!parentId.equals(other.parentId))
            return false;
        if (sort == null) {
            if (other.sort != null)
                return false;
        }
        else if (!sort.equals(other.sort))
            return false;
        if (icon == null) {
            if (other.icon != null)
                return false;
        }
        else if (!icon.equals(other.icon))
            return false;
        if (insertTime == null) {
            if (other.insertTime != null)
                return false;
        }
        else if (!insertTime.equals(other.insertTime))
            return false;
        if (updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.resourceType == null) ? 0 : this.resourceType.hashCode());
        result = prime * result + ((this.permission == null) ? 0 : this.permission.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.sort == null) ? 0 : this.sort.hashCode());
        result = prime * result + ((this.icon == null) ? 0 : this.icon.hashCode());
        result = prime * result + ((this.insertTime == null) ? 0 : this.insertTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TPermissionObj (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(resourceType);
        sb.append(", ").append(permission);
        sb.append(", ").append(url);
        sb.append(", ").append(parentId);
        sb.append(", ").append(sort);
        sb.append(", ").append(icon);
        sb.append(", ").append(insertTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
