/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRolePermissionObj implements Serializable {

    private static final long serialVersionUID = -1605982163;

    private Integer id;
    private Integer permissionId;
    private Integer roleId;

    public TRolePermissionObj() {}

    public TRolePermissionObj(TRolePermissionObj value) {
        this.id = value.id;
        this.permissionId = value.permissionId;
        this.roleId = value.roleId;
    }

    public TRolePermissionObj(
        Integer id,
        Integer permissionId,
        Integer roleId
    ) {
        this.id = id;
        this.permissionId = permissionId;
        this.roleId = roleId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRolePermissionObj other = (TRolePermissionObj) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (permissionId == null) {
            if (other.permissionId != null)
                return false;
        }
        else if (!permissionId.equals(other.permissionId))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.permissionId == null) ? 0 : this.permissionId.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRolePermissionObj (");

        sb.append(id);
        sb.append(", ").append(permissionId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
