/*
 * This file is generated by jOOQ.
*/
package com.guoguo.domain.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleObj implements Serializable {

    private static final long serialVersionUID = -78170971;

    private Integer id;
    private String  roleName;
    private String  description;
    private String  available;

    public TRoleObj() {}

    public TRoleObj(TRoleObj value) {
        this.id = value.id;
        this.roleName = value.roleName;
        this.description = value.description;
        this.available = value.available;
    }

    public TRoleObj(
        Integer id,
        String  roleName,
        String  description,
        String  available
    ) {
        this.id = id;
        this.roleName = roleName;
        this.description = description;
        this.available = available;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAvailable() {
        return this.available;
    }

    public void setAvailable(String available) {
        this.available = available;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRoleObj other = (TRoleObj) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!roleName.equals(other.roleName))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (available == null) {
            if (other.available != null)
                return false;
        }
        else if (!available.equals(other.available))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.available == null) ? 0 : this.available.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoleObj (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(description);
        sb.append(", ").append(available);

        sb.append(")");
        return sb.toString();
    }
}
